FROM keymetrics/pm2:12-alpine
ENV NODE_ENV "staging"
RUN apk add --no-cache ca-certificates && adduser -D unicorn
WORKDIR /home/unicorn
COPY . ./unicorn-board
WORKDIR /home/unicorn/unicorn-board
RUN npm install
USER unicorn
ENTRYPOINT [ "node", "./node_modules/.bin/webpack-dev-server","--config", "./webpack.config.js", "--host", "0.0.0.0" ]
EXPOSE 9003
